server:
  port: 80
  servlet:
    session:
      timeout: 600s

spring:
  thymeleaf:
    enabled: false
  datasource:
    name: qabbs  #数据库名
    url: jdbc:mysql://localhost:3306/qabbs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true #url
    username: USER  #用户名
    password: USER  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    port: 6379
    host: "localhost"

mybatis:
  type-aliases-package: matsk.mszdqabbs.Pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    max-history: 30
    max-size: 10MB
    path: "./logs"
    name: "./logs/mszdqabbs.log"
  level:
    root: INFO
